name: CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Repository
        uses: actions/Checkout@v3

      - name:  Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.11'

      - name: Install pipx and poetry
        run: |
          pip install pipx
          pipx ensurepath
          pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Add poetry virtualenv to PATH
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Lint code with ruff
        uses: chartboost/ruff-action@v1
        with:
          args: "check"

      - name: Format code with ruff
        uses: chartboost/ruff-action@v1
        with:
          args: "format --check"

      - name: Run Pyright type check
        uses: jakebailey/pyright-action@v2

