name: Dependency Analysis

on:
    pull_request:
        branches: [main]

jobs:
    dependency-review:
        runs-on: ubuntu-latest
        steps:
            - name: Dependency Review
              uses: actions/checkout@v4

            - name: Dependency Review
              if: ${{github.event_name == 'pull_request'}}
              uses: actions/dependency-review-action@v4
              with:
                comment-summary-in-pr: always

